[global]

# By default, Streamlit checks if the Python watchdog module is available and, if not,
# prints a warning asking for you to install it. The watchdog module is not required,
# it's just an optimization. If you know you don't want to install watchdog, you can
# suppress this warning by setting this to True.
disableWatchdogWarning = false

# By default, Streamlit displays a warning when a user sets both a widget default
# value in the function defining the widget and a widget value via the widget's key
# in st.session_state.
showWarningOnDirectExecution = true

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not run as the result of most kinds of
# "reruns" (such as after a widget interaction), but rather allows you to control
# rerunning via `st.rerun()`.
toolbarMode = "auto"

[runner]

# Allows you to type a variable or string by itself in a single line of Python code
# to write it to the app.
magicEnabled = true

# Install a Python tracer to allow you to stop or pause your script at any point
# and introspect it. As a side-effect, this slows down your script's execution.
installTracer = false

# Sets the MPLBACKEND environment variable to Agg inside Streamlit to prevent
# Python crashing.
fixMatplotlib = true

# Run the Python Garbage Collector after each script execution. This can help to
# reduce memory usage in Streamlit apps, but could also cause app slowdowns.
postScriptGC = true

# Handle script rerun requests immediately, rather than waiting for script execution
# to reach a yield point. This makes Streamlit much more responsive to user
# interaction, but it can break some functionality that depends on script execution
# order.
fastReruns = true

[server]

# List of folders that should not be watched for changes. This impacts both the
# behavior of `streamlit run` and `st.rerun()`.
# Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
# Allowed values: * "auto" : Streamlit will attempt to use the watchdog module, and
#                   falls back to polling if watchdog is not available.
#                 * "watchdog" : Force Streamlit to use the watchdog module.
#                 * "poll" : Force Streamlit to always use polling.
#                 * "none" : Streamlit will not watch files.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# ensure that this is set to the same value across all replicas to ensure they all
# share the same secret.
# Default: randomly generated secret key.
cookieSecret = "cattle-breed-classifier-secret-key-2025"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The address where the server will listen for client and browser connections.
# Use this if you want to bind the server to a specific address. If set, the server
# will only be accessible from this address, and not from any other address.
# Default: (unset)
# address =

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for added
# security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added
# security.
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded through the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

# Enable serving files from a `static` directory in the running app's directory.
enableStaticServing = false

[browser]

# Internet address where users should point their browsers in order to connect to
# the app. Can be IP address or DNS name and path.
# This is used to: - Set the correct URL for CORS and XSRF protection purposes.
#                  - Show the URL on the terminal
#                  - Open the browser
# Default: 'localhost'
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

# Port where users should point their browsers in order to connect to the app.
# This is used to: - Set the correct URL for CORS and XSRF protection purposes.
#                  - Show the URL on the terminal
#                  - Open the browser
# Default: whatever value is set in server.port.
serverPort = 8501

[mapbox]

# Configure Streamlit to use a custom Mapbox
# token for elements like st.pydeck_chart and st.map.
# To get a token for yourself, create an account at
# https://mapbox.com. It's free (for moderate usage levels)!
# Default: ""
token = ""

[deprecation]

# Set to false to disable the deprecation warning for the file uploader encoding.
showfileUploaderEncoding = true

# Set to false to disable the deprecation warning for using the global pyplot instance.
showPyplotGlobalUse = true

[theme]

# Primary accent color for interactive elements.
primaryColor = "#3498db"

# Background color for the main content area.
backgroundColor = "#0e1117"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#262730"

# Color used for almost all text.
textColor = "#fafafa"

# Font family for all text in Streamlit apps.
font = "sans serif"